package view.gui;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;
import model.*;

/**
 *
 * @author alexiaruegut & paucanmil
 */
public class InterfazAdmin extends javax.swing.JFrame {

    /**
     * Creates new form InterfazAdmin
     */
    private ArrayList<Cine> listaCines = new ArrayList<>();
    private Cine cineSeleccionado = new Cine();
    public static DefaultListModel<String> modeloSalas = new DefaultListModel<>();
    public static DefaultTableModel modeloPelis = new DefaultTableModel(
            new Object[][]{},
            new String[]{"Titulo", "Sala", "Crear Sesión", "Ver Sesiones"}
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; 
        }
    };

    public InterfazAdmin() {
        initComponents();

        setPlaceholder(jTextFieldNameCine, "Introduce el nombre del cine");
        setPlaceholder(jTextFieldUbiCine, "Introduce la ubicación del cine");
        setPlaceholder(jTextFieldNumSalasCine, "Introduce el número de salas");
        setPlaceholder(jTextFieldPrecioBaseCine, "Introduce el precio base de entradas");
        
        setPlaceholder(jTextFieldNamePeli, "Introduce el título de la película");
        setPlaceholder(jTextFieldDuracionPeli, "Introduce la duración de la película");
        setPlaceholder(jTextFieldDescripcionPeli, "Introduce la sinopsis de la película");

        jTextFieldNameCine.setForeground(new java.awt.Color(150, 150, 150));

        jTabbedPane1.removeAll();
        jTabbedPane1.addTab("Home", jPanel1);  
        jTabbedPane1.addTab("Crear Cine", jPanel2);     
        jTabbedPane1.addTab("Cine", jPanel3);
        jTabbedPane1.addTab("Salas", jPanel4);
        jTabbedPane1.addTab("Películas", jPanel5);
        jTabbedPane1.addTab("Sesiones", jPanel6);
        jTabbedPane1.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSide = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jComboBoxCines = new javax.swing.JComboBox<>();
        jButtonAddCine = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelnombrecine = new javax.swing.JLabel();
        jTextFieldNameCine = new javax.swing.JTextField();
        jLabelubicine = new javax.swing.JLabel();
        jTextFieldUbiCine = new javax.swing.JTextField();
        jLabelnumsalascine = new javax.swing.JLabel();
        jTextFieldNumSalasCine = new javax.swing.JTextField();
        jLabelpreciobasecine = new javax.swing.JLabel();
        jTextFieldPrecioBaseCine = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePelis = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListSalas = new javax.swing.JList<>();
        jButtonCrearSalaForm = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButtonCrearSalaForm1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxTipoSala = new javax.swing.JComboBox<>();
        jLabelnombrecine1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButtonCrearSala = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabelnombrePELI = new javax.swing.JLabel();
        jTextFieldNamePeli = new javax.swing.JTextField();
        jLabelDURACIONPELI = new javax.swing.JLabel();
        jTextFieldDuracionPeli = new javax.swing.JTextField();
        jLabelnumIDIOMApeli = new javax.swing.JLabel();
        jLabeldescripcionpeli = new javax.swing.JLabel();
        jTextFieldDescripcionPeli = new javax.swing.JTextField();
        jButtonCancelarPeli = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jComboBoxSalaPeli = new javax.swing.JComboBox<>();
        jComboBoxIdiomaPeli = new javax.swing.JComboBox<>();
        jLabelnumIDIOMApeli1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabelnombrePELI1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelnombrePELI2 = new javax.swing.JLabel();
        jTextFieldNamePELI1 = new javax.swing.JTextField();
        jLabelnombrePELI3 = new javax.swing.JLabel();
        jTextFieldNamePELI2 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabelnombrePELI4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSide.setBackground(java.awt.SystemColor.activeCaption);

        jButton6.setBackground(java.awt.SystemColor.activeCaption);
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/home.png"))); // NOI18N
        jButton6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jComboBoxCines.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Crear cine"}));
        jComboBoxCines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCinesActionPerformed(evt);
            }
        });

        jButtonAddCine.setText("+");
        jButtonAddCine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCineActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("CINES");
        jLabel3.setToolTipText("");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/admin.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ADMINISTRACIÓN");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.setName(""); // NOI18N
        jLabel5.setPreferredSize(null);

        javax.swing.GroupLayout jPanelSideLayout = new javax.swing.GroupLayout(jPanelSide);
        jPanelSide.setLayout(jPanelSideLayout);
        jPanelSideLayout.setHorizontalGroup(
            jPanelSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelSideLayout.createSequentialGroup()
                        .addComponent(jComboBoxCines, 0, 158, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAddCine))
                    .addGroup(jPanelSideLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelSideLayout.setVerticalGroup(
            jPanelSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddCine, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );

        getContentPane().add(jPanelSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 441));

        jTabbedPane1.setBackground(new java.awt.Color(249, 249, 249));

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Bienvenid@, Admin");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Maneja cines, sus salas y películas");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Selecciona un cine para empezar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        jPanel2.setBackground(new java.awt.Color(249, 249, 249));

        jLabelnombrecine.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelnombrecine.setText("NOMBRE CINE");

        jTextFieldNameCine.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldNameCine.setToolTipText("");
        jTextFieldNameCine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameCineActionPerformed(evt);
            }
        });

        jLabelubicine.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelubicine.setText("UBICACIÓN");

        jLabelnumsalascine.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelnumsalascine.setText("Nº SALAS");

        jLabelpreciobasecine.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelpreciobasecine.setText("PRECIO BASE ENTRADAS");

        jButton7.setBackground(new java.awt.Color(91, 137, 186));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setText("CANCELAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(91, 137, 186));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setText("CREAR");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.activeCaption);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREAR DE CINE");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 82, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelpreciobasecine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelnumsalascine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelnombrecine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelubicine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNameCine)
                    .addComponent(jTextFieldUbiCine)
                    .addComponent(jTextFieldNumSalasCine)
                    .addComponent(jTextFieldPrecioBaseCine, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelnombrecine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNameCine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelubicine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUbiCine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelnumsalascine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNumSalasCine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelpreciobasecine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPrecioBaseCine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        jPanel3.setBackground(new java.awt.Color(249, 249, 249));

        jTablePelis.setModel(modeloPelis);
        jScrollPane1.setViewportView(jTablePelis);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(java.awt.SystemColor.activeCaption);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PELÍCULAS");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jListSalas.setModel(modeloSalas);
        jScrollPane2.setViewportView(jListSalas);

        jButtonCrearSalaForm.setText("+");
        jButtonCrearSalaForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearSalaFormActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(java.awt.SystemColor.activeCaption);
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SALAS");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButtonCrearSalaForm1.setText("+");
        jButtonCrearSalaForm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearSalaForm1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jButtonCrearSalaForm1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonCrearSalaForm)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCrearSalaForm)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addComponent(jButtonCrearSalaForm1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(40, 40, 40))
        );

        jTabbedPane1.addTab("tab3", jPanel3);

        jPanel4.setBackground(new java.awt.Color(249, 249, 249));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(java.awt.SystemColor.activeCaption);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CREAR SALA");

        jComboBoxTipoSala.setModel(new javax.swing.DefaultComboBoxModel<>(
            java.util.Arrays.stream(enumTipoSala.values())
            .map(Enum::name)
            .toArray(String[]::new)
        ));
        jComboBoxTipoSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoSalaActionPerformed(evt);
            }
        });

        jLabelnombrecine1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelnombrecine1.setText("TIPO DE SALA");

        jButton9.setBackground(new java.awt.Color(91, 137, 186));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton9.setText("CANCELAR");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButtonCrearSala.setBackground(new java.awt.Color(91, 137, 186));
        jButtonCrearSala.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCrearSala.setText("CREAR");
        jButtonCrearSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearSalaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelnombrecine1)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBoxTipoSala, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonCrearSala, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabelnombrecine1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTipoSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButtonCrearSala))
                .addContainerGap(220, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", jPanel4);

        jPanel5.setBackground(new java.awt.Color(249, 249, 249));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(java.awt.SystemColor.activeCaption);
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CREAR PELÍCULA");

        jLabelnombrePELI.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelnombrePELI.setText("TÍTULO");

        jTextFieldNamePeli.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldNamePeli.setToolTipText("");
        jTextFieldNamePeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamePeliActionPerformed(evt);
            }
        });

        jLabelDURACIONPELI.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDURACIONPELI.setText("DURACIÓN");

        jTextFieldDuracionPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDuracionPeliActionPerformed(evt);
            }
        });

        jLabelnumIDIOMApeli.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelnumIDIOMApeli.setText("IDIOMA                       SALA");

        jLabeldescripcionpeli.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabeldescripcionpeli.setText("SINOPSIS");

        jTextFieldDescripcionPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescripcionPeliActionPerformed(evt);
            }
        });

        jButtonCancelarPeli.setBackground(new java.awt.Color(91, 137, 186));
        jButtonCancelarPeli.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCancelarPeli.setText("CANCELAR");
        jButtonCancelarPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarPeliActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(91, 137, 186));
        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton11.setText("CREAR");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jComboBoxSalaPeli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { null }));
        jComboBoxSalaPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSalaPeliActionPerformed(evt);
            }
        });

        jComboBoxIdiomaPeli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Catalán", "Inglés" }));

        jLabelnumIDIOMApeli1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDescripcionPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonCancelarPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelnumIDIOMApeli)
                                        .addComponent(jLabelDURACIONPELI))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelnumIDIOMApeli1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelnombrePELI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldNamePeli, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldDuracionPeli, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jComboBoxIdiomaPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jComboBoxSalaPeli, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGap(43, 43, 43)))
                            .addComponent(jLabeldescripcionpeli, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelnombrePELI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNamePeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDURACIONPELI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDuracionPeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabelnumIDIOMApeli1)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabelnumIDIOMApeli)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSalaPeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxIdiomaPeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabeldescripcionpeli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDescripcionPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelarPeli)
                    .addComponent(jButton11))
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("tab5", jPanel5);

        jPanel6.setBackground(new java.awt.Color(249, 249, 249));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(java.awt.SystemColor.activeCaption);
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CREAR SESIÓN /PRÓXIMAMENTE");

        jLabelnombrePELI1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelnombrePELI1.setText("TÍTULO");

        jLabel10.setText("(AQUÍ Q SE VEA LA PELI SELECCIONADA)");

        jLabelnombrePELI2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelnombrePELI2.setText("FECHA (YYYY-MM-DD)");

        jTextFieldNamePELI1.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldNamePELI1.setToolTipText("");
        jTextFieldNamePELI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamePELI1ActionPerformed(evt);
            }
        });

        jLabelnombrePELI3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelnombrePELI3.setText("HORA (HH:MM:SS)");

        jTextFieldNamePELI2.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldNamePELI2.setToolTipText("");
        jTextFieldNamePELI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamePELI2ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(91, 137, 186));
        jButton12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton12.setText("CANCELAR");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(91, 137, 186));
        jButton13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton13.setText("CREAR");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabelnombrePELI4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelnombrePELI4.setText("SALA");

        jLabel12.setText("(AQUÍ Q SE VEA LA SALA DE LA PELI)");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabelnombrePELI1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelnombrePELI3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelnombrePELI2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldNamePELI1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldNamePELI2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel12)
                            .addComponent(jLabelnombrePELI4, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelnombrePELI1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabelnombrePELI4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabelnombrePELI2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNamePELI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelnombrePELI3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNamePELI2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton13))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab6", jPanel6);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, -39, 420, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBoxCinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCinesActionPerformed
        String seleccionado = (String) jComboBoxCines.getSelectedItem();
        if (seleccionado == null) {
            return;
        }

        if ("Seleccionar cine".equals(seleccionado)) {
            jTabbedPane1.setSelectedIndex(0);
        } else if ("Crear cine".equals(seleccionado)) {
            jTabbedPane1.setSelectedIndex(0);
        } else {
            System.out.println("Cine seleccionado: " + seleccionado);
            for (Cine cine : listaCines) {
                if (cine.getNombre().equals(seleccionado)) {
                    cineSeleccionado = cine;
                }
            }
            modeloSalas.removeAllElements();
            for (Sala sala : cineSeleccionado.getSalas()) {
                modeloSalas.addElement(sala.getTipoSala().toString());
            }
            for (int i = 0; i < modeloPelis.getRowCount(); i++) {
                modeloPelis.removeRow(i);
            }
            for (Sala sala : cineSeleccionado.getSalas()) {
                for (Pelicula peli : sala.getPeliculas()) {
                    String[] rowData = {peli.getTitulo(), sala.getTipoSala().toString()};
                    modeloPelis.addRow(rowData);
                }
            }
            jTabbedPane1.setSelectedIndex(2);
        }
    }//GEN-LAST:event_jComboBoxCinesActionPerformed

    private void jButtonAddCineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCineActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButtonAddCineActionPerformed

    private void jTextFieldNameCineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameCineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameCineActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String nombre = jTextFieldNameCine.getText().trim();
        String ubicacion = jTextFieldUbiCine.getText().trim();
        String numSalasStr = jTextFieldNumSalasCine.getText().trim();
        String precioBaseStr = jTextFieldPrecioBaseCine.getText().trim();

        if (nombre.isEmpty() || nombre.equals("Introduce el nombre del cine")
                || ubicacion.isEmpty() || ubicacion.equals("Introduce la ubicación del cine")
                || numSalasStr.isEmpty() || numSalasStr.equals("Introduce el número de salas")
                || precioBaseStr.isEmpty() || precioBaseStr.equals("Introduce el precio base de entradas")) {
            System.out.println("Por favor, completa todos los campos correctamente.");
            return;
        }

        int totalSalas, precioBase;
        try {
            totalSalas = Integer.parseInt(numSalasStr);
            precioBase = Integer.parseInt(precioBaseStr);
        } catch (NumberFormatException e) {
            System.out.println("El número de salas y el precio base deben ser numéricos.");
            return;
        }

        Cine nuevoCine = new Cine(nombre, ubicacion, totalSalas, precioBase, new ArrayList<>());
        cineSeleccionado = nuevoCine;
        listaCines.add(nuevoCine);
        actualizarComboBoxCines(listaCines);

        jTextFieldNameCine.setText("");
        jTextFieldUbiCine.setText("");
        jTextFieldNumSalasCine.setText("");
        jTextFieldPrecioBaseCine.setText("");

        jTabbedPane1.setSelectedIndex(0);

        System.out.println("Cine creado con éxito: " + nuevoCine.getNombre());
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButtonCrearSalaFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearSalaFormActionPerformed
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jButtonCrearSalaFormActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButtonCrearSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearSalaActionPerformed
        enumTipoSala selectedEnum = enumTipoSala.valueOf((String) jComboBoxTipoSala.getSelectedItem());
        cineSeleccionado.setSalas(new ArrayList<>(Arrays.asList(new Sala(selectedEnum))));
        modeloSalas.addElement(selectedEnum.toString());
        System.out.println(selectedEnum);
        System.out.println(modeloSalas.getElementAt(0));
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButtonCrearSalaActionPerformed

    private void jTextFieldNamePeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamePeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamePeliActionPerformed

    private void jButtonCancelarPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarPeliActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButtonCancelarPeliActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        String nombre = jTextFieldNamePeli.getText().trim();
        String duracion = jTextFieldDuracionPeli.getText().trim();
        String selectedIdioma = (String) jComboBoxIdiomaPeli.getSelectedItem();
        enumTipoSala selectedSala = enumTipoSala.valueOf((String) jComboBoxTipoSala.getSelectedItem());
        String descripcion = jTextFieldDescripcionPeli.getText().trim();

        if (nombre.isEmpty() || nombre.equals("Introduce el nombre de la película")
                || duracion.isEmpty() || duracion.equals("Introduce la duración de la película")
                || descripcion.isEmpty() || descripcion.equals("Introduce la sinopsis de la película")) {
            System.out.println("Por favor, completa todos los campos correctamente.");
            return;
        }

        int intDuracion;
        try {
            intDuracion = Integer.parseInt(duracion);
        } catch (NumberFormatException e) {
            System.out.println("La duración de la película debe ser numérica.");
            return;
        }

        Pelicula nuevaPeli = new Pelicula(nombre, intDuracion, selectedIdioma, descripcion);
        Sala selectedSalaObj = new Sala();
        for (Sala sala : cineSeleccionado.getSalas()) {
            if (sala.getTipoSala().equals(selectedSala)) {
                selectedSalaObj = sala;
            }
        }

        selectedSalaObj.setPeliculas(nuevaPeli);

        String[] rowData = {nuevaPeli.getTitulo(), selectedSala.toString()};
        modeloPelis.addRow(rowData);
        actualizarComboBoxCines(listaCines);

        jTextFieldNameCine.setText("");
        jTextFieldUbiCine.setText("");
        jTextFieldNumSalasCine.setText("");
        jTextFieldPrecioBaseCine.setText("");

        jTabbedPane1.setSelectedIndex(2);
;
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTextFieldNamePELI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamePELI1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamePELI1ActionPerformed

    private void jTextFieldNamePELI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamePELI2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamePELI2ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jTextFieldDuracionPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDuracionPeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDuracionPeliActionPerformed

    private void jComboBoxTipoSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoSalaActionPerformed
        //jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jComboBoxTipoSalaActionPerformed

    private void jButtonCrearSalaForm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearSalaForm1ActionPerformed
        ArrayList<Sala> salas = new ArrayList<>();
        for (Sala sala : cineSeleccionado.getSalas()) {
            salas.add(sala);
        }
        actualizarComboBoxSalas(salas);
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_jButtonCrearSalaForm1ActionPerformed

    private void jComboBoxSalaPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSalaPeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSalaPeliActionPerformed

    private void jTextFieldDescripcionPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescripcionPeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescripcionPeliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAddCine;
    private javax.swing.JButton jButtonCancelarPeli;
    private javax.swing.JButton jButtonCrearSala;
    private javax.swing.JButton jButtonCrearSalaForm;
    private javax.swing.JButton jButtonCrearSalaForm1;
    private javax.swing.JComboBox<String> jComboBoxCines;
    private javax.swing.JComboBox<String> jComboBoxIdiomaPeli;
    private javax.swing.JComboBox<String> jComboBoxSalaPeli;
    private javax.swing.JComboBox<String> jComboBoxTipoSala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDURACIONPELI;
    private javax.swing.JLabel jLabeldescripcionpeli;
    private javax.swing.JLabel jLabelnombrePELI;
    private javax.swing.JLabel jLabelnombrePELI1;
    private javax.swing.JLabel jLabelnombrePELI2;
    private javax.swing.JLabel jLabelnombrePELI3;
    private javax.swing.JLabel jLabelnombrePELI4;
    private javax.swing.JLabel jLabelnombrecine;
    private javax.swing.JLabel jLabelnombrecine1;
    private javax.swing.JLabel jLabelnumIDIOMApeli;
    private javax.swing.JLabel jLabelnumIDIOMApeli1;
    private javax.swing.JLabel jLabelnumsalascine;
    private javax.swing.JLabel jLabelpreciobasecine;
    private javax.swing.JLabel jLabelubicine;
    private javax.swing.JList<String> jListSalas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelSide;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTablePelis;
    private javax.swing.JTextField jTextFieldDescripcionPeli;
    private javax.swing.JTextField jTextFieldDuracionPeli;
    private javax.swing.JTextField jTextFieldNameCine;
    private javax.swing.JTextField jTextFieldNamePELI1;
    private javax.swing.JTextField jTextFieldNamePELI2;
    private javax.swing.JTextField jTextFieldNamePeli;
    private javax.swing.JTextField jTextFieldNumSalasCine;
    private javax.swing.JTextField jTextFieldPrecioBaseCine;
    private javax.swing.JTextField jTextFieldUbiCine;
    // End of variables declaration//GEN-END:variables

    private void setPlaceholder(JTextField textField, String placeholder) {
        textField.setText(placeholder);
        textField.setForeground(new java.awt.Color(150, 150, 150));

        textField.addFocusListener(new java.awt.event.FocusListener() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (textField.getText().equals(placeholder)) {
                    textField.setText("");
                    textField.setForeground(new java.awt.Color(0, 0, 0));
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (textField.getText().trim().isEmpty()) {
                    textField.setText(placeholder);
                    textField.setForeground(new java.awt.Color(150, 150, 150));
                }
            }
        });
    }

    public void actualizarComboBoxCines(ArrayList<Cine> cines) {
        jComboBoxCines.removeAllItems(); 
        jComboBoxCines.addItem("Seleccionar cine"); 
        for (Cine cine : cines) {
            jComboBoxCines.addItem(cine.getNombre());
        }
    }

    public void actualizarComboBoxSalas(ArrayList<Sala> salas) {
        jComboBoxSalaPeli.removeAllItems(); 
        for (Sala sala : salas) {
            jComboBoxSalaPeli.addItem(sala.getTipoSala().toString());
        }
    }

    public static void agregarFilaDesdeString(javax.swing.JTable table, String data) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        String[] valores = data.split(",");

        model.addRow(valores);
    }
}
