/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.gui;

import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import model.Cine;

/**
 *
 * @author alexiaruegut
 */
public class InterfazAdmin extends javax.swing.JFrame {

    /**
     * Creates new form InterfazAdmin
     */
    private ArrayList<Cine> listaCines = new ArrayList<>();

    public InterfazAdmin() {
        initComponents();

        // Agregar placeholder inicial
        setPlaceholder(jTextFieldNameCine, "Introduce el nombre del cine");
        setPlaceholder(jTextFieldUbiCine, "Introduce la ubicación del cine");
        setPlaceholder(jTextFieldNumSalasCine, "Introduce el número de salas");
        setPlaceholder(jTextFieldPrecioBaseCine, "Introduce el precio base de entradas");

        jTextFieldNameCine.setForeground(new java.awt.Color(150, 150, 150));

        // Reorganizar las pestañas:
        // Queremos que la pestaña 0 ("Home") sea la vista principal,
        // la pestaña 1 ("Crear Cine") contenga el formulario para crear cines.
        jTabbedPane1.removeAll();
        jTabbedPane1.addTab("Home", jPanel1);           // Vista por defecto (puede ser un panel vacío o con información)
        jTabbedPane1.addTab("Crear Cine", jPanel2);       // Formulario de creación de cine
        jTabbedPane1.addTab("Otro", jPanel3);             // Otra pestaña (si la necesitas)
        jTabbedPane1.setSelectedIndex(0); // Mostrar "Home" por defecto
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSide = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jComboBoxCines = new javax.swing.JComboBox<>();
        jButtonAddCine = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelnombrecine = new javax.swing.JLabel();
        jTextFieldNameCine = new javax.swing.JTextField();
        jLabelubicine = new javax.swing.JLabel();
        jTextFieldUbiCine = new javax.swing.JTextField();
        jLabelnumsalascine = new javax.swing.JLabel();
        jTextFieldNumSalasCine = new javax.swing.JTextField();
        jLabelpreciobasecine = new javax.swing.JLabel();
        jTextFieldPrecioBaseCine = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSide.setBackground(new java.awt.Color(51, 255, 51));

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/home.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jComboBoxCines.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cine 1", "Cine 2", "Cine 3", "Cine 4" }));
        jComboBoxCines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCinesActionPerformed(evt);
            }
        });

        jButtonAddCine.setText("+");
        jButtonAddCine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCineActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("CINES");
        jLabel3.setToolTipText("");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/admin.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ADMINISTRACIÓN");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.setName(""); // NOI18N
        jLabel5.setPreferredSize(null);

        javax.swing.GroupLayout jPanelSideLayout = new javax.swing.GroupLayout(jPanelSide);
        jPanelSide.setLayout(jPanelSideLayout);
        jPanelSideLayout.setHorizontalGroup(
            jPanelSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSideLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(41, 41, 41))
            .addGroup(jPanelSideLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelSideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelSideLayout.createSequentialGroup()
                        .addComponent(jComboBoxCines, 0, 158, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAddCine))
                    .addGroup(jPanelSideLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelSideLayout.setVerticalGroup(
            jPanelSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSideLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddCine, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(jButton2)
                .addGap(36, 36, 36)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanelSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 441));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        jLabelnombrecine.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelnombrecine.setText("NOMBRE CINE");

        jTextFieldNameCine.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldNameCine.setToolTipText("");
        jTextFieldNameCine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameCineActionPerformed(evt);
            }
        });

        jLabelubicine.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelubicine.setText("UBICACIÓN");

        jLabelnumsalascine.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelnumsalascine.setText("Nº SALAS");

        jLabelpreciobasecine.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelpreciobasecine.setText("PRECIO BASE ENTRADAS");

        jButton7.setBackground(new java.awt.Color(91, 137, 186));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setText("CANCELAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(91, 137, 186));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setText("CREAR");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelpreciobasecine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelnumsalascine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelnombrecine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelubicine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldNameCine)
                        .addComponent(jTextFieldUbiCine)
                        .addComponent(jTextFieldNumSalasCine)
                        .addComponent(jTextFieldPrecioBaseCine, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addContainerGap(86, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(jLabelnombrecine)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextFieldNameCine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabelubicine)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextFieldUbiCine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabelnumsalascine)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextFieldNumSalasCine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabelpreciobasecine)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextFieldPrecioBaseCine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton7)
                        .addComponent(jButton8))
                    .addContainerGap(59, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(186, 186, 186))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel2)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 1, -1, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    // Por ejemplo, podría volver a la pestaña "Home" o realizar otra acción
    jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBoxCinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCinesActionPerformed
       // Aquí puedes agregar la lógica para cuando se seleccione un cine
    String seleccionado = (String) jComboBoxCines.getSelectedItem();
    if ("Seleccionar cine".equals(seleccionado)) {
        // Mostrar la vista por defecto (Home)
        jTabbedPane1.setSelectedIndex(0);
    } else {
        System.out.println("Cine seleccionado: " + seleccionado);
        // Aquí podrías cambiar la vista o mostrar detalles del cine
    }
    }//GEN-LAST:event_jComboBoxCinesActionPerformed

    private void jButtonAddCineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCineActionPerformed
// Cambiar a la pestaña "Crear Cine" (índice 1)
    jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButtonAddCineActionPerformed

    private void jTextFieldNameCineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameCineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameCineActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String nombre = jTextFieldNameCine.getText().trim();
        String ubicacion = jTextFieldUbiCine.getText().trim();
        String numSalasStr = jTextFieldNumSalasCine.getText().trim();
        String precioBaseStr = jTextFieldPrecioBaseCine.getText().trim();

        // Verificar que no queden los placeholders o campos vacíos
        if (nombre.isEmpty() || nombre.equals("Introduce el nombre del cine")
                || ubicacion.isEmpty() || ubicacion.equals("Introduce la ubicación del cine")
                || numSalasStr.isEmpty() || numSalasStr.equals("Introduce el número de salas")
                || precioBaseStr.isEmpty() || precioBaseStr.equals("Introduce el precio base de entradas")) {
            System.out.println("Por favor, completa todos los campos correctamente.");
            return;
        }

        // Convertir los campos numéricos
        int totalSalas, precioBase;
        try {
            totalSalas = Integer.parseInt(numSalasStr);
            precioBase = Integer.parseInt(precioBaseStr);
        } catch (NumberFormatException e) {
            System.out.println("El número de salas y el precio base deben ser numéricos.");
            return;
        }

        // Crear el cine usando el constructor del modelo
        Cine nuevoCine = new Cine(nombre, ubicacion, totalSalas, precioBase, new ArrayList<>());
        // Agregar el cine a la lista y actualizar el ComboBox
        listaCines.add(nuevoCine);
        actualizarComboBoxCines(listaCines);

        // Limpiar los campos del formulario
        jTextFieldNameCine.setText("");
        jTextFieldUbiCine.setText("");
        jTextFieldNumSalasCine.setText("");
        jTextFieldPrecioBaseCine.setText("");

        // Opcional: volver a la pestaña "Home" luego de crear el cine
        jTabbedPane1.setSelectedIndex(0);

        System.out.println("Cine creado con éxito: " + nuevoCine.getNombre());
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         // Al cancelar, volver a la pestaña "Home"
    jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonAddCine;
    private javax.swing.JComboBox<String> jComboBoxCines;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelnombrecine;
    private javax.swing.JLabel jLabelnumsalascine;
    private javax.swing.JLabel jLabelpreciobasecine;
    private javax.swing.JLabel jLabelubicine;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelSide;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldNameCine;
    private javax.swing.JTextField jTextFieldNumSalasCine;
    private javax.swing.JTextField jTextFieldPrecioBaseCine;
    private javax.swing.JTextField jTextFieldUbiCine;
    // End of variables declaration//GEN-END:variables

    private void setPlaceholder(JTextField textField, String placeholder) {
        textField.setText(placeholder);
        textField.setForeground(new java.awt.Color(150, 150, 150));

        textField.addFocusListener(new java.awt.event.FocusListener() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (textField.getText().equals(placeholder)) {
                    textField.setText("");
                    textField.setForeground(new java.awt.Color(0, 0, 0));
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (textField.getText().trim().isEmpty()) {
                    textField.setText(placeholder);
                    textField.setForeground(new java.awt.Color(150, 150, 150));
                }
            }
        });
    }

    public void actualizarComboBoxCines(ArrayList<Cine> cines) {
        jComboBoxCines.removeAllItems(); // Limpia los valores previos
        jComboBoxCines.addItem("Seleccionar cine"); // Opción por defecto
        for (Cine cine : cines) {
            jComboBoxCines.addItem(cine.getNombre());
        }
    }
}
